### ISSUE TITLE
Unable to encode to B64. Returning null

### ISSUE THREAD

**Issue by Milimeter** [jpmehedi/animated_horizontal_calendar#3]
Using the package Docs code example i got the error below:
Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      List.length= (dart:core-patch/growable_array.dart:246:12)
#1      concat (package:tripledes_nullsafety/src/utils.dart:99:19)
#2      pkcs7Pad (package:tripledes_nullsafety/src/utils.dart:62:3)
#3      BaseEngine.process (package:tripledes_nullsafety/src/engine.dart:31:7)
#4      BlockCipher.encode (package:tripledes_nullsafety/tripledes_nullsafety.dart:19:25)
#5      BlockCipher.encodeB64 (package:tripledes_nullsafety/tripledes_nullsafety.dart:32:26)

**Comment by jpmehedi** [comment]
Now
